name: Release

on:
  push:
    branches: ["production"]

  workflow_dispatch:
    inputs:
      tag:
        required: true
        description: The tag to release
        type: choice
        default: stable
        options:
          - stable
          - next

jobs:
  verify:
    uses: ./.github/workflows/verify.yml

  release:
    runs-on: ubuntu-latest
    needs: [verify]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-pnpm
      - name: Release
        run: pnpm release --tag ${{ inputs.tag }}
